// src/pages/savings/SavingsRegister.jsx
import React, { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { db } from "../../components/firebase";
import { doc, getDoc, setDoc, serverTimestamp } from "firebase/firestore";
import './savings.css';

const SavingsRegister = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    accountId: "",
    password: "",
    confirmPassword: "",
  });
  const [error, setError] = useState("");

  const handleChange = (e) =>
    setFormData({ ...formData, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    const { name, phone, accountId, password, confirmPassword } = formData;

    if (!name || !phone || !accountId || !password || !confirmPassword) {
      setError("All fields are required.");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    try {
      // Check if account exists (generated by admin)
      const accountRef = doc(db, "savingsAccounts", accountId);
      const accountSnap = await getDoc(accountRef);

      if (!accountSnap.exists()) {
        setError("Invalid Account ID. Please contact the admin.");
        return;
      }

      const accountData = accountSnap.data();

      if (accountData.name) {
        setError("Account ID already taken. Please contact the admin.");
        return;
      }

      // Update account with member info
      await setDoc(
        doc(db, "savingsAccounts", accountId),
        {
          name,
          phone,
          password,
          createdAt: serverTimestamp(),
          balance: accountData.balance || 0,
        },
        { merge: true }
      );

      // Redirect to member dashboard
      navigate(`/savings-member-dashboard/${accountId}`);
    } catch (err) {
      console.error(err);
      setError("Failed to register account. Please try again.");
    }
  };

  return (
    <div className="savings-dashboard-container">
      <h1>Register Your Savings Account</h1>
      <p>Enter your details and your unique Account ID provided by the admin.</p>

      <Link to="/savings-dashboard" className="btn-secondary" style={{ marginBottom: "20px" }}>
        Back to Dashboard
      </Link>

      <form className="savings-form" onSubmit={handleSubmit}>
        <input
          type="text"
          name="name"
          placeholder="Full Name"
          value={formData.name}
          onChange={handleChange}
          className="savings-input"
        />
        <input
          type="text"
          name="phone"
          placeholder="Phone Number"
          value={formData.phone}
          onChange={handleChange}
          className="savings-input"
        />
        <input
          type="text"
          name="accountId"
          placeholder="Account ID (given by admin)"
          value={formData.accountId}
          onChange={handleChange}
          className="savings-input"
        />
        <input
          type="password"
          name="password"
          placeholder="Password"
          value={formData.password}
          onChange={handleChange}
          className="savings-input"
        />
        <input
          type="password"
          name="confirmPassword"
          placeholder="Confirm Password"
          value={formData.confirmPassword}
          onChange={handleChange}
          className="savings-input"
        />

        {error && <div className="error">{error}</div>}

        <button type="submit" className="btn-primary">
          Register Account
        </button>
      </form>
    </div>
  );
};

export default SavingsRegister;
